default: &default
  adapter: postgresql
  encoding: unicode
  # Increased for better performance in development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "tarot_api" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "password" } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  # Clear pattern for database names - IMPORTANT: this should always take precedence
  # over any conflicting environment variables (DB_NAME, etc.)
  database: tarot_api_<%= ENV["DATABASE_URL"] ? nil : Rails.env %>
  url: <%= ENV["DATABASE_URL"] %>
  # Connection pool settings
  reaping_frequency: <%= ENV.fetch("DB_REAPING_FREQUENCY") { 10 } %>
  checkout_timeout: <%= ENV.fetch("DB_POOL_TIMEOUT") { 5 } %>

development:
  <<: *default
  # Development-specific settings
  schema_search_path: public
  min_messages: notice

# IMPORTANT: The test database configuration is completely isolated from development
test:
  <<: *default
  # Test-specific settings
  min_messages: warning
  pool: <%= ENV.fetch("TEST_DB_POOL") { 5 } %>

# For staging and production with replica support
# This configuration uses the makara adapter when DB_REPLICA_ENABLED=true
staging:
  <% if ENV["DB_REPLICA_ENABLED"] == "true" %>
  # Makara configuration for primary/replica setup
  adapter: postgresql
  encoding: unicode
  prepared_statements: false
  adapter: 'makara_postgresql'
  makara:
    sticky: true
    blacklist_duration: 30
    connections:
      - role: primary
        name: primary
        database: tarot_api_<%= ENV["DATABASE_URL"] ? nil : Rails.env %>
        host: <%= ENV["DB_PRIMARY_HOST"] || ENV["DB_HOST"] %>
        port: <%= ENV["DB_PRIMARY_PORT"] || ENV["DB_PORT"] || 5432 %>
        username: <%= ENV["DB_PRIMARY_USER"] || ENV["DB_USERNAME"] %>
        password: <%= ENV["DB_PRIMARY_PASSWORD"] || ENV["DB_PASSWORD"] %>
      - role: replica
        name: replica
        database: tarot_api_<%= ENV["DATABASE_URL"] ? nil : Rails.env %>
        host: <%= ENV["DB_REPLICA_HOST"] || ENV["DB_HOST"] %>
        port: <%= ENV["DB_REPLICA_PORT"] || ENV["DB_PORT"] || 5432 %>
        username: <%= ENV["DB_REPLICA_USER"] || ENV["DB_USERNAME"] %>
        password: <%= ENV["DB_REPLICA_PASSWORD"] || ENV["DB_PASSWORD"] %>
  <% else %>
  <<: *default
  <% end %>
  pool: <%= ENV.fetch("DB_POOL_SIZE") { 10 } %>

production:
  <% if ENV["DB_REPLICA_ENABLED"] == "true" %>
  # Makara configuration for primary/replica setup
  adapter: postgresql
  encoding: unicode
  prepared_statements: false
  adapter: 'makara_postgresql'
  makara:
    sticky: true
    blacklist_duration: 30
    connections:
      - role: primary
        name: primary
        database: tarot_api_<%= ENV["DATABASE_URL"] ? nil : Rails.env %>
        host: <%= ENV["DB_PRIMARY_HOST"] || ENV["DB_HOST"] %>
        port: <%= ENV["DB_PRIMARY_PORT"] || ENV["DB_PORT"] || 5432 %>
        username: <%= ENV["DB_PRIMARY_USER"] || ENV["DB_USERNAME"] %>
        password: <%= ENV["DB_PRIMARY_PASSWORD"] || ENV["DB_PASSWORD"] %>
      - role: replica
        name: replica
        database: tarot_api_<%= ENV["DATABASE_URL"] ? nil : Rails.env %>
        host: <%= ENV["DB_REPLICA_HOST"] || ENV["DB_HOST"] %>
        port: <%= ENV["DB_REPLICA_PORT"] || ENV["DB_PORT"] || 5432 %>
        username: <%= ENV["DB_REPLICA_USER"] || ENV["DB_USERNAME"] %>
        password: <%= ENV["DB_REPLICA_PASSWORD"] || ENV["DB_PASSWORD"] %>
  <% else %>
  <<: *default
  <% end %>
  pool: <%= ENV.fetch("DB_POOL_SIZE") { 20 } %>
  prepared_statements: true
  statement_limit: 200
  sslmode: require 