imports:
  # Core infrastructure components
  network: network.yaml
  database: database.yaml
  cache: cache.yaml
  storage: storage.yaml
  ecs: ecs.yaml
  monitoring: monitoring.yaml
  
  # Domain management
  mainDomain: domain.yaml       # Primary domain (tarotapi.cards)
  altDomain: alt-domain.yaml    # Alternative domain (tarot.cards)

variables:
  # Main configuration settings - shared across all components
  tarotapi:
    # Set default values that can be overridden by Pulumi stack config
    type: object
    default:
      projectName: tarot-api
      environment: development
      domain: tarotapi.cards
      altDomain: tarot.cards
      region: mx-central-1
      enableCostSaving: true
      # Database settings
      dbName: tarot_api
      dbUsername: tarot_api
      # Replica configuration 
      enableReplica: false  # Replicas always enabled in production, optional in staging
      # Connection pool settings
      dbPoolSize: 10        # Default pool size
      redisPoolSize: 15     # Default Redis pool size
      maxThreads: 5         # Default thread count

outputs:
  # Merge outputs from all components for easy access
  infrastructureInfo:
    type: object
    value:
      vpc:
        id: ${network.vpcId}
        publicSubnets: ${network.publicSubnets}
        privateSubnets: ${network.privateSubnets}
      
      database:
        address: ${database.dbAddress}
        port: ${database.dbPort}
        name: ${database.dbName}
        username: ${database.dbUsername}
        replica:
          enabled: ${database.hasReplica}
          address: ${database.dbReplicaAddress}
          port: ${database.dbReplicaPort}
      
      cache:
        address: ${cache.redisHost}
        port: ${cache.redisPort}
      
      storage:
        bucketName: ${storage.appBucketName}
        cdnDomain: ${storage.cdnDomainName}
      
      compute:
        ecrRepository: ${ecs.ecrRepositoryUrl}
        albDns: ${ecs.albDns}
        instanceIp: ${ecs.instanceIp}
      
      domains:
        primary:
          name: ${mainDomain.apiDns}
          status: ${mainDomain.registrationStatus}
          nameservers: ${mainDomain.dnsNameServers}
          certificateArn: ${mainDomain.certificateArn}
        
        alternative:
          name: ${altDomain.altRegistrationStatus == "error" ? "not-registered" : "tarot.cards"}
          status: ${altDomain.altRegistrationStatus}
          nameservers: ${altDomain.altDnsNameServers}
          certificateArn: ${altDomain.altCertificateArn}
  
  # For shell scripts and automation
  shellFormat:
    type: object
    value:
      DOMAIN: ${mainDomain.apiDns}
      ALT_DOMAIN: ${altDomain.altRegistrationStatus == "error" ? "" : "tarot.cards"}
      DB_HOST: ${database.dbAddress}
      DB_PORT: ${database.dbPort}
      DB_NAME: ${database.dbName}
      DB_USERNAME: ${database.dbUsername}
      DB_REPLICA_ENABLED: ${database.hasReplica}
      DB_PRIMARY_HOST: ${database.dbAddress}
      DB_PRIMARY_PORT: ${database.dbPort}
      DB_REPLICA_HOST: ${database.dbReplicaAddress}
      DB_REPLICA_PORT: ${database.dbReplicaPort}
      DB_POOL_SIZE: ${tarotapi:environment == "production" ? "20" : "10"}
      REDIS_URL: redis://${cache.redisHost}:${cache.redisPort}
      AWS_BUCKET: ${storage.appBucketName}
      ECR_REPO: ${ecs.ecrRepositoryUrl}
      INSTANCE_IP: ${ecs.instanceIp} 