name: tarotapi
runtime: yaml
description: Infrastructure for the Tarot API project

config:
  aws:region: mx-central-1
  tarotapi:environment: development
  tarotapi:projectName: tarotapi
  tarotapi:repoName: abdul-hamid-achik/tarotapi
  tarotapi:domainName: tarotapi.cards
  tarotapi:altDomainName: tarot.cards
  tarotapi:ollamaApiKey: ""
  tarotapi:openaiApiKey: ""
  tarotapi:enableCostSaving: true
  pulumi:disable_default_providers:
    - aws
  # Pulumi Cloud state management configuration

variables:
  # Get values from config
  projectName:
    fn::fromConfig: tarotapi:projectName
  domainName:
    fn::fromConfig: tarotapi:domainName
  altDomainName:
    fn::fromConfig: tarotapi:altDomainName
  environment:
    fn::fromConfig: tarotapi:environment
  stackName: ${pulumi.stack}
  
  # Network Configuration
  vpcCidr: "10.0.0.0/16"
  publicSubnetEastCidr: "10.0.3.0/24"
  publicSubnetWestCidr: "10.0.4.0/24"
  
  # Instance Types - Cost-effective but scalable options
  dbInstanceClass: "db.t4g.micro"  # ARM-based for better price/performance
  cacheInstanceClass: "cache.t4g.micro"  # ARM-based for better price/performance
  
  # ECS Configuration - Minimal but sufficient for startup
  ecsTaskCpu: "256"
  ecsTaskMemory: "512"
  
  # Tags
  commonTags:
    Project: ${projectName}
    Environment: ${stackName}
    ManagedBy: "pulumi"

resources:
  vpc:
    type: "aws:ec2:Vpc"
    properties:
      cidrBlock: ${vpcCidr}
      enableDnsHostnames: true
      enableDnsSupport: true
      tags:
        Name: "${projectName}-vpc-${stackName}"
        Project: ${projectName}
        Environment: ${stackName}
        ManagedBy: "pulumi"

  publicSubnetEast:
    type: "aws:ec2:Subnet"
    properties:
      vpcId: ${vpc.id}
      cidrBlock: ${publicSubnetEastCidr}
      availabilityZone: "mx-central-1a"
      mapPublicIpOnLaunch: true
      tags:
        Name: "${projectName}-public-subnet-east-${stackName}"
        Project: ${projectName}
        Environment: ${stackName}
        ManagedBy: "pulumi"

  publicSubnetWest:
    type: "aws:ec2:Subnet"
    properties:
      vpcId: ${vpc.id}
      cidrBlock: ${publicSubnetWestCidr}
      availabilityZone: "mx-central-1b"
      mapPublicIpOnLaunch: true
      tags:
        Name: "${projectName}-public-subnet-west-${stackName}"
        Project: ${projectName}
        Environment: ${stackName}
        ManagedBy: "pulumi"

  dbSubnetGroup:
    type: "aws:rds:SubnetGroup"
    properties:
      name: "${projectName}-db-subnet-${stackName}"
      subnetIds:
        - ${publicSubnetEast.id}
        - ${publicSubnetWest.id}
      description: "Subnet group for RDS instances"
      tags:
        Name: "${projectName}-db-subnet-group-${stackName}"
        Project: ${projectName}
        Environment: ${stackName}
        ManagedBy: "pulumi"

  dbPassword:
    type: "random:RandomString"
    properties:
      length: 16
      special: false
      upper: true
      number: true

  dbInstance:
    type: "aws:rds:Instance"
    properties:
      identifier: "${projectName}-db-${stackName}"
      engine: "postgres"
      engineVersion: "14.13"
      instanceClass: ${dbInstanceClass}
      allocatedStorage: 20
      dbSubnetGroupName: ${dbSubnetGroup.name}
      username: "tarotapi"
      password: ${dbPassword.result}
      skipFinalSnapshot: true
      backupRetentionPeriod: 7
      autoMinorVersionUpgrade: true
      performanceInsightsEnabled: false
      tags:
        Name: "${projectName}-db-${stackName}"
        Project: ${projectName}
        Environment: ${stackName}
        ManagedBy: "pulumi"

  cacheSubnetGroup:
    type: "aws:elasticache:SubnetGroup"
    properties:
      name: "${projectName}-cache-subnet-${stackName}"
      description: "Subnet group for ElastiCache instances"
      subnetIds:
        - ${publicSubnetEast.id}
        - ${publicSubnetWest.id}
      tags:
        Name: "${projectName}-cache-subnet-group-${stackName}"
        Project: ${projectName}
        Environment: ${stackName}
        ManagedBy: "pulumi"

  cacheCluster:
    type: "aws:elasticache:Cluster"
    properties:
      clusterId: "${projectName}-redis-${stackName}"
      engine: "redis"
      nodeType: ${cacheInstanceClass}
      numCacheNodes: 1
      parameterGroupName: "default.redis7"
      port: 6379
      subnetGroupName: ${cacheSubnetGroup.name}
      securityGroupIds: []  # We'll configure this later
      applyImmediately: true
      autoMinorVersionUpgrade: true
      tags:
        Name: "${projectName}-redis-${stackName}"
        Project: ${projectName}
        Environment: ${stackName}
        ManagedBy: "pulumi"

  s3Bucket:
    type: "aws:s3:Bucket"
    properties:
      bucket: "${projectName}-storage-${stackName}"
      acl: "private"
      versioning:
        enabled: true
      lifecycleRules:
        - enabled: true
          transitions:
            - days: 30
              storageClass: "STANDARD_IA"
            - days: 90
              storageClass: "GLACIER"
      tags:
        Name: "${projectName}-storage-${stackName}"
        Project: ${projectName}
        Environment: ${stackName}
        ManagedBy: "pulumi"

  dnsZone:
    type: "aws:route53:Zone"
    properties:
      name: ${domainName}
      tags:
        Name: "${projectName}-dns-zone-${stackName}"
        Project: ${projectName}
        Environment: ${stackName}
        ManagedBy: "pulumi"

  certificate:
    type: "aws:acm:Certificate"
    properties:
      domainName: ${domainName}
      validationMethod: "DNS"
      subjectAlternativeNames:
        - ${altDomainName}
      tags:
        Name: "${projectName}-cert-${stackName}"
        Project: ${projectName}
        Environment: ${stackName}
        ManagedBy: "pulumi"

  ecsCluster:
    type: "aws:ecs:Cluster"
    properties:
      name: "${projectName}-cluster-${stackName}"
      settings:
        - name: "containerInsights"
          value: "disabled"
      tags:
        Name: "${projectName}-cluster-${stackName}"
        Project: ${projectName}
        Environment: ${stackName}
        ManagedBy: "pulumi"

  ecsTaskExecutionRole:
    type: "aws:iam:Role"
    properties:
      assumeRolePolicy: |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": { "Service": "ecs-tasks.amazonaws.com" },
              "Action": "sts:AssumeRole"
            }
          ]
        }
      managedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
      tags:
        Name: "${projectName}-ecs-exec-role-${stackName}"
        Project: ${projectName}
        Environment: ${stackName}
        ManagedBy: "pulumi"

  containerRepository:
    type: "aws:ecr:Repository"
    properties:
      name: "${projectName}-${stackName}"
      imageScanningConfiguration:
        scanOnPush: true
      imageTagMutability: "MUTABLE"
      tags:
        Name: "${projectName}-ecr-${stackName}"
        Project: ${projectName}
        Environment: ${stackName}
        ManagedBy: "pulumi"

outputs:
  dbEndpoint:
    value: ${dbInstance.endpoint}
  redisEndpoint:
    value: ${cacheCluster.cacheNodes[0].address}
  ecsClusterId:
    value: ${ecsCluster.name}
  containerRegistry:
    value: ${containerRepository.repositoryUrl}
  s3BucketName:
    value: ${s3Bucket.bucket}
