name: tarot-api-infra
runtime: yaml
description: infrastructure for tarot api project with zero-downtime deployments
config:
  aws:region: mx-central-1  # mexico region
  environment:
    default: dev
  domain:
    default: tarotapi.cards
  project-name:
    default: tarot-api
  enable-cost-saving:
    default: true
  repo-url:
    default: https://github.com/yourusername/tarot_api 