name: Build CI image

on:
  push:
    branches: [main]
    paths:
      - 'Dockerfile'
  pull_request:
    paths:
      - 'Dockerfile'
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-push:
    name: Build and push CI image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION || 'mx-central-1' }}
      
      - name: Build and push container image
        run: |
          # Set the GitHub Container Registry URL for development
          export CONTAINER_REGISTRY="ghcr.io/${{ github.repository_owner }}/tarot-api"
          
          # Get short commit hash
          COMMIT_HASH="${{ github.sha }}"
          SHORT_HASH="${COMMIT_HASH:0:7}"
          echo "Using commit hash: $SHORT_HASH"
          
          # Build the image 
          bundle exec rake container:build[development]
          
          # Push to GitHub Container Registry
          bundle exec rake container:push[development] 